// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMrlAsbhojE5nLuSecDvc2YUIi5aUwTuQ',
    appId: '1:396154653346:web:28c94d3feae8b928cae5fb',
    messagingSenderId: '396154653346',
    projectId: 'tictactekber',
    authDomain: 'tictactekber.firebaseapp.com',
    storageBucket: 'tictactekber.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwzLfaeQOQLyO3NoOyZpa6zR1ZpnqUZ4w',
    appId: '1:396154653346:android:6260bb27798b1307cae5fb',
    messagingSenderId: '396154653346',
    projectId: 'tictactekber',
    storageBucket: 'tictactekber.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfe-WJx79QeOedjEo_HXiSC85hFBfG-gw',
    appId: '1:396154653346:ios:503938be02c37a4fcae5fb',
    messagingSenderId: '396154653346',
    projectId: 'tictactekber',
    storageBucket: 'tictactekber.firebasestorage.app',
    iosBundleId: 'com.example.tictactekber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfe-WJx79QeOedjEo_HXiSC85hFBfG-gw',
    appId: '1:396154653346:ios:503938be02c37a4fcae5fb',
    messagingSenderId: '396154653346',
    projectId: 'tictactekber',
    storageBucket: 'tictactekber.firebasestorage.app',
    iosBundleId: 'com.example.tictactekber',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMrlAsbhojE5nLuSecDvc2YUIi5aUwTuQ',
    appId: '1:396154653346:web:4842d5a650fb7b13cae5fb',
    messagingSenderId: '396154653346',
    projectId: 'tictactekber',
    authDomain: 'tictactekber.firebaseapp.com',
    storageBucket: 'tictactekber.firebasestorage.app',
  );
}
